// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWvwEF7qAJ1M-z1rI--yyEYscKXlufUW0',
    appId: '1:929791059157:web:a0f6444e2ab7bbb496ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    authDomain: 'test-adecc.firebaseapp.com',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
    measurementId: 'G-V9D8QPF544',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zpk9utQiQcmaJur4ZcmPpmi308XiroI',
    appId: '1:929791059157:android:d404db9fa7c7259b96ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfaRNuxgrUU5LpucFYWJUSIx5pduhr0S0',
    appId: '1:929791059157:ios:e849e83d6cbad45096ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
    iosBundleId: 'com.example.sky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfaRNuxgrUU5LpucFYWJUSIx5pduhr0S0',
    appId: '1:929791059157:ios:e849e83d6cbad45096ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
    iosBundleId: 'com.example.sky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWvwEF7qAJ1M-z1rI--yyEYscKXlufUW0',
    appId: '1:929791059157:web:c2958854b6c675f296ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    authDomain: 'test-adecc.firebaseapp.com',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
    measurementId: 'G-GKDWWQ92KP',
  );
}
